apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: labs-deployment
  namespace: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: labs-deployment
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Pods
      pods:
        metric:
          name: jvm_memory_percentage
        target:
          type: Value
          averageValue: 30
    - type: Pods
      pods:
        metric:
          name: http_server_requests_seconds_count_sum
        target:
          type: AverageValue
          averageValue: 100


$ while true; do curl http://localhost/api/v1/labs;  done;
